# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

variables:
  ConnectedServiceName: 'bba9cf9c-0553-4678-bf21-c65e7839ec1d'
  WebAppKind: 'webApp'
  WebAppName: 'demowebapp001'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
jobs:
  - deployment: DeployWebAppOnAzureVM
    displayName: 'Deploy Web App to Azure virtual Machine'
    environment: 'azurevmdeploye'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'specific'
              project: '8757f6d8-0ada-4daa-9ef5-b9750be607d4'
              pipeline: '17'
              buildVersionToDownload: 'latest'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'appservicedep-serviceconnection'
              appType: 'webApp'
              WebAppName: 'demowebapp001'
              packageForLinux: '$(System.DefaultWorkingDirectory)'

          
          # - task: DownloadBuildArtifacts@1
          #   inputs:
          #     buildType: 'specific'
          #     project: '8757f6d8-0ada-4daa-9ef5-b9750be607d4'
          #     pipeline: '17'
          #     buildVersionToDownload: 'latest'
          #     downloadType: 'single'
          #     artifactName: 'drop'
          #     downloadPath: '$(System.ArtifactsDirectory)'
            
          # - task: AzureRmWebAppDeployment@4
          #   inputs:
          #       ConnectionType: 'AzureRM'
          #       azureSubscription: 'Free Trial (de2f44e1-3fea-4643-80a3-072f00a5e753)'
          #       appType: 'webApp'
          #       WebAppName: 'demowebapp001'
          #       #package: '$(System.ArtifactsDirectory)/drop/WebApp.zip'
          #       Package: '$(System.DefaultWorkingDirectory)/**/*.zip'
          
          