# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

variables:
  ConnectedServiceName: 'bba9cf9c-0553-4678-bf21-c65e7839ec1d'
  WebAppKind: 'webApp'
  WebAppName: 'demowebapp001'
  #solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution: '**\*.sln'

stages:
- stage: Build
  displayName: "Build Stage"
  jobs: 
  - job: BuildJob
    pool:
      vmImage: 'windows-latest'

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
- stage: "Deploytoappfirst"
  dependsOn: Build
  jobs:
      - deployment: DeployWebAppOnAzureAppService
        displayName: 'Deploy Web App to Azure AppService'
        environment: 'DeploytoAppOne'
        strategy:
          runOnce:
            deploy:
              steps:
              - task: DownloadBuildArtifacts@1
                inputs:
                  buildType: 'specific'
                  project: '8757f6d8-0ada-4daa-9ef5-b9750be607d4'
                  pipeline: '17'
                  buildVersionToDownload: 'latest'
                  downloadType: 'single'
                  artifactName: 'drop'
                  downloadPath: '$(System.ArtifactsDirectory)'
              - task: AzureWebApp@1
                inputs:
                  azureSubscription: 'appservicedep-serviceconnection'
                  appType: 'webApp'
                  appName: 'WebApp2'
                  package: '$(System.DefaultWorkingDirectory)'
                  deploymentMethod: 'zipDeploy'
              
- stage: "DeploytoApptwo"  
  dependsOn: Deploytoappfirst
  jobs:
      - deployment: DeployWebAppOnAzureAppServicetwo
        displayName: 'Deploy Web App to Azure AppService two'
        environment: "DeploytoApptwo"
        strategy:
          runOnce:
            deploy:
              steps:
              - task: DownloadBuildArtifacts@1
                inputs:
                  buildType: 'specific'
                  project: '8757f6d8-0ada-4daa-9ef5-b9750be607d4'
                  pipeline: '17'
                  buildVersionToDownload: 'latest'
                  downloadType: 'single'
                  artifactName: 'drop'
                  downloadPath: '$(System.ArtifactsDirectory)'
              - task: AzureWebApp@1
                inputs:
                  azureSubscription: 'appservicedep-serviceconnection'
                  appType: 'webApp'
                  appName: 'demowebapp001'
                  package: '$(System.DefaultWorkingDirectory)'
                  deploymentMethod: 'zipDeploy'         
